### ISSUE TITLE
Problem with UI

### ISSUE THREAD

**Issue by maz323f** [JadHajjar/FindIt-CSII#10]
![Skjermbilde 2024-04-09 010546](https://github.com/JadHajjar/FindIt-CSII/assets/56172550/08293113-08cc-4248-89ec-bbaa6c2d9be9)

I got this grey box in the middle of the user interface, making it impossible to click the icons in the middle.a

**Comment by JadHajjar** [comment]
This has been fixed in 0.9.4.3
